name: Generate Isometric

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push to output branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin output
          git checkout output
          cp profile-3d-contrib/profile-night-green.svg isometric.svg
          git add isometric.svg
          git commit -m "Update isometric graph to dark version" || exit 0
          git push
